name: A workflow for my Hello World file
on: push

jobs:

  build:
    strategy:
      matrix:
       include:
         - name: "RuTa"
         - name: "Vasia" 
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "${{ matrix.name }}"
