name: Deploy BigData
env:
  default_branch: 'develop'
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        name: 
        - parse_abp_csv_cf
        - crop_csv_from_excel_cf
        - trigger_composer_dag_cf
        - crop_csv_from_excel_mar_cf
        - crop_csv_from_excel_mpc_cf        
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3      
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          ls src/cloud_functions/crop_csv_from_excel_cf/
          cd src/cloud_functions
          ls */requirements.txt
          for requirement in $(ls */requirements.txt); do pip install -r "$requirement" || exit 1; done
          for requirement in $(ls */requirements-default.txt); do pip install -r "$requirement" || exit 1; done
      - name: Run Test
        run: |
          echo something: $CLOUD_FUNCTION_NAME
          python --version
        env:
          CLOUD_FUNCTION_NAME: "${{ matrix.name }}"
        
          
        

        
