name: A workflow for my Hello World file
on: push

jobs:

  build:
    strategy:
      matrix:
        name: 
        - parse_abp_csv_cf
        - crop_csv_from_excel_cf
        - trigger_composer_dag_cf
        - crop_csv_from_excel_mar_cf
        - crop_csv_from_excel_mpc_cf        
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "${{ matrix.name }}"
