name: Deploy BigData
env:
  default_branch: 'develop'
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        name: 
        - parse_abp_csv_cf
        - crop_csv_from_excel_cf
        - trigger_composer_dag_cf
        - crop_csv_from_excel_mar_cf
        - crop_csv_from_excel_mpc_cf        
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3      
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.11
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          cd src/cloud_functions/$CLOUD_FUNCTION_NAME || exit 0
          [ ! -d "tests/" ] && echo "There is no tests for function $CLOUD_FUNCTION_NAME" && exit 0
          [ -e "requirements.txt" ] && pip install -r "requirements.txt" || echo "No requirements.txt file found"
          [ -e "requirements-default.txt" ] && pip install -r "requirements-default.txt" || echo "No requirements-default.txt file found"
          python -m unittest || exit 1        
        env:
          CLOUD_FUNCTION_NAME: "${{ matrix.name }}"        

        
          
        

        
