name: Deploy BigData
env:
  default_branch: 'develop'
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        name: 
        - parse_abp_csv_cf
        - crop_csv_from_excel_cf
        - trigger_composer_dag_cf
        - crop_csv_from_excel_mar_cf
        - crop_csv_from_excel_mpc_cf        
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3      
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src/cloud_functions/$CLOUD_FUNCTION_NAME || exit 1
          pwd
          [ -e "requirements.txt" ] && pip install -r "requirements.txt" || echo "No requirements.txt file found"
          [ -e "requirements-default" ] && pip install -r "requirements-default" || echo "No requirements-default file found"
        env:
          CLOUD_FUNCTION_NAME: "${{ matrix.name }}"        
      - name: Run Test
        run: |
          echo something: $CLOUD_FUNCTION_NAME
          python --version
        env:
          CLOUD_FUNCTION_NAME: "${{ matrix.name }}"
        
          
        

        
