name: Deploy BigData
env:
  default_branch: 'develop'
on: [push]
jobs:
  test:
    strategy:
      matrix:
        name: 
        - parse_abp_csv_cf
        - crop_csv_from_excel_cf
        - trigger_composer_dag_cf
        - crop_csv_from_excel_mar_cf
        - crop_csv_from_excel_mpc_cf        
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: ./action-a
        with:
          CLOUD_FUNCTION_NAME: "${{ matrix.name }}"
      - run: "python --version"
      - run: "printenv"
      - run: "echo cloud function name: $INPUT_CLOUD_FUNCTION_NAME"
        
